name: mnemo_app
description: MnemoApp — Master your subjects, one breakthrough at a time.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.3.0
  firebase_core: ^4.6.0
  flutter_dotenv: ^6.0.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  firebase_storage: ^13.3.0
  image_picker: ^1.2.1
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env