name: mnemo_app
description: MnemoApp — Master your subjects, one breakthrough at a time.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.2.0
  connectivity_plus: ^7.1.1
  firebase_auth: ^6.3.0
  firebase_core: ^4.6.0
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  firebase_storage: ^13.3.0
  image_picker: ^1.2.1
  file_picker: ^11.0.2
  http: ^1.6.0
  pdf: ^3.11.0
  file_saver: ^0.4.0
  path_provider: ^2.1.0
  printing: ^5.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true